- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update Pacman
    become: true
    pacman:
      update_cache: yes
      upgrade: yes
  - name: Install OpenSSH
    become: true
    pacman:
      name: openssh
  - name: Clone Yay
    ansible.builtin.git:
      repo: https://aur.archlinux.org/yay.git
      dest: ./yay
  - name: Install Yay
    shell: cd yay && makepkg -si --noconfirm && cd .. && rm -rif yay
  - name: Configure Yay
    become: true
    shell: cp ./makepkg.conf /etc/makepkg.conf
    tags:
      - base

  tasks:
    - include_tasks: tasks/pacman.yml
    - include_tasks: tasks/infosec.yml
    - include_tasks: tasks/kde.yml
    - include_tasks: tasks/dev-setup.yml
    - include_tasks: tasks/packages-install.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/db-setup.yml
    - include_tasks: tasks/bluetooth.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/neovim.yml
    # - include_tasks: tasks/boot.yml
