- name: Install Bluez Packages 
  become: true
  pacman:
    name: bluez,bluez-utils
  tags:
    - base

- name: Enable Bluetooth service
  become: true
  shell: sudo systemctl enable bluetooth
  tags:
    - base
