- name: Set systemd-boot config
  shell: sed -i "/options/c options root=PARTUUID=$(blkid -s PARTUUID -o value /dev/nvme0n1p3) rw ipv6.disable=1 resume=PARTUUID=$(blkid -s PARTUUID -o value /dev/nvme0n1p2) quiet" /boot/loader/entries/arch.conf
  tags:
    - base
    - boot
