- name: Install MariaDB
  become: true
  pacman:
    name: mariadb
  tags:
    - base
    - dev
    - db

- name: Configure MariaDB
  become: true
  shell: mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  tags:
    - base
    - dev
    - db

- name: Enable MariaDB service
  become: true
  shell: sudo systemctl enable mariadb
  tags:
    - base
    - dev
    - db

- name: Install MongoDB
  shell: yay -S --noconfirm aur/mongodb-bin aur/mongodb-compass aur/mongodb-tools-bin aur/mongosh-bin
  tags:
    - base
    - dev
    - db

- name: Enable MongoDB service
  become: true
  shell: sudo systemctl enable mongodb 
  tags:
    - base
    - dev
    - db
