- name: Install Development Packages (Pacman)
  become: true
  pacman:
    name: 
      - fzf
      - bat
      - code
      - neovim
      - zsh
      - zsh-completions
      - xclip
      - perl
      - tree
      - unrar
      - python
      - php
      - php-gd
      - man-db
      - tldr
      - autoconf
      - automake
      - aws-cli-v2
      - docker
      - docker-compose
      - composer
      - fd
      - filezilla
      - freerdp
      - gawk
      - helm
      - kubectl
      - konsole
      - mysql-workbench
      - postgresql
      - putty
      - pycharm-community-edition
      - intellij-idea-community-edition
      - stow
      - virt-manager
  tags:
    - dev

- name: Install Development Packages (AUR)
  shell: yay -S --noconfirm aur/nvim-packer-git aur/azure-cli-bin aur/nodejs-n aur/postman-bin aur/python-grip
  tags:
    - dev

- name: Install Node JS
  become: true
  shell: sudo n latest
  tags:
    - dev

- name: Enable Docker service
  become: true
  shell: sudo systemctl enable docker
  tags:
    - dev

- name: Set Docker permission
  become: true
  shell: sudo usermod -aG docker $USER
  tags:
    - dev

- name: Install QEMU & virt-manager
  become: true
  pacman:
    name: qemu-desktop,virt-manager,libvirt,dnsmasq,iptables
  tags:
    - dev

- name: Add user to libvirt group
  become: true
  shell: usermod -aG libvirt $(whoami)
  tags:
    - dev

- name: Enable QEMU
  become: true
  shell: sudo systemctl enable libvirtd
  tags:
    - dev

- name: Start QEMU
  become: true
  shell: sudo systemctl start libvirtd
  tags:
    - dev
