- name: Install Docker & docker-compose
  become: true
  pacman:
    name: docker,docker-compose

- name: Enable Docker service
  become: true
  shell: sudo systemctl enable docker

- name: Install QEMU & virt-manager
  become: true
  pacman:
    name: qemu-desktop,virt-manager,libvirt,dnsmasq,iptables

- name: Add user to libvirt group
  become: true
  shell: usermod -aG libvirt $(whoami)

- name: Enable QEMU
  become: true
  shell: sudo systemctl enable libvirtd

- name: Start QEMU
  become: true
  shell: sudo systemctl start libvirtd


- name: Install QEMU & virt-manager
  become: true
  pacman:
    name: minikube 

- name: Install Minikube
  become: true
  shell: minikube config set driver kvm2
