- name: Install Default Packages 
  become: true
  pacman:
    name: stow
  tags:
    - base
    - dotfiles
    - stow
# - name: Start ssh-agent
#   shell: eval "$(ssh-agent -s)"
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:AxelZublena/dotfiles'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    accept_hostkey: yes
    version: master
    update: yes
  tags:
    - base
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/dotfiles && stow -v -t $HOME *
  tags:
    - base
    - dotfiles
    - stow
