- name: Install Default Packages 
  become: true
  pacman:
    name: stow
  tags:
    - base
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: rm $HOME/.zshrc && cd $HOME/dotfiles && stow -v -t $HOME *
  tags:
    - base
    - dotfiles
    - stow
