- name: Add ArchStrike repo
  become: true
  shell: sudo echo -e "[archstrike]\nServer = https://mirror.archstrike.org/\$arch/\$repo" >> /etc/pacman.conf
  tags:
    - infosec

- name: Update Pacman cache
  become: true
  pacman:
    update_cache: yes
  tags:
    - infosec

- name: Install ArchStrike keyring
  become: true
  community.general.pacman_key:
    id: 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
    url: https://archstrike.org/keyfile.asc
    state: present
  tags:
    - infosec

- name: Install ArchStrike Keyring Packages 
  become: true
  pacman:
    name: 
      - archstrike-keyring
      - archstrike-mirrorlist
  tags: 
    - infosec

- name: Install InfoSec Packages (Pacman)
  become: true
  pacman:
    name: 
      - aircrack-ng
      - binutils
      - binwalk
      - bison
      - carwhisperer
      - dnsmasq
      - ghidra
      - gnu-netcat
      - hashcat
      - hexedit
      - john
      - lynis
      - net-tools
      - nmap
      - perl-image-exiftool
      - pgpdump
      - redfang
      - sha3sum
      - sonic-visualiser
      - imagemagick
      - tcpdump
      - traceroute
      - ubertooth-git
      - wireshark-qt
  tags:
    - base
    - infosec

- name: Install InfoSec Packages (AUR)
  shell: yay -S --noconfirm aur/hash-identifier-git aur/networkminer aur/redress aur/steghide
  tags:
    - infosec
