- name: Add ArchStrike repo
  become: true
  shell: sudo echo -e "[archstrike]\nServer = https://mirror.archstrike.org/\$arch/\$repo" >> /etc/pacman.conf
  tags:
    - base

- name: Update Pacman
  become: true
  pacman:
    update_cache: yes
    upgrade: yes
  tags:
    - base


- name: Install InfoSec packages
  become: true
  pacman:
    name: 
      - aircrack-ng
      - binutils
      - binwalk
      - bison
      - carwhisperer
      - dnsmasq
      - ghidra
      - gnu-netcat
      - hashcat
      - hexedit
      - john
      - lynis
      - net-tools
      - nmap
      - perl-image-exiftool
      - pgpdump
      - redfang
      - sha3sum
      - sonic-visualiser
      - imagemagick
      - tcpdump
      - traceroute
      - ubertooth-git
      - wireshark-qt
  tags:
    - base

- name: Install Packages
  shell: yay -S --noconfirm aur/hash-identifier-git aur/hidattack aur/networkminer aur/redress aur/steghide
  tags:
    - base
