# - name: Install Neovim plugins 
#   become: true
#   shell: nvim --headless +'PlugInstall --sync' +'PlugUpdate' +qall
#   tags:
#     - nvim

# - name: Install Language Servers
#   become: true
#   shell: sudo npm install -g pyright typescript typescript-language-server vim-language-server svelte-language-server @tailwindcss/language-server dockerfile-language-server-nodejs vscode-langservers-extracted
#   tags:
#     - nvim
#
# - name: Install Language Servers 2
#   become: true
#   shell: yarn global add yaml-language-server
#   tags:
#     - nvim
