- name: Update Pacman
  become: true
  pacman:
    update_cache: yes
  tags:
    - base

- name: Install Default packages (Pacman)
  become: true
  pacman:
    name: 
      - htop
      - neofetch
      - cups
      - cups-pdf
      - amd-ucode
      - f2fs-tools
      - gzip
      - pipewire
      - pipewire-pulse
  tags:
    - base

- name: Install Default Applications (Pacman)
  become: true
  pacman:
    name: 
      - firefox-developer-edition
      - discord
      - flameshot
      - obs-studio
      - steam
      - vlc
      - qbittorrent
      - kdenlive
      - blender
      - mpv
      - gerbera
  tags:
    - base

- name: Install Default Packages (AUR)
  shell: yay -S --noconfirm aur/ms-teams-for-linux-bin aur/freeoffice aur/figma-linux-bin aur/google-chrome aur/inkdrop aur/mellowplayer
  tags:
    - base

- name: Enable Cups service
  become: true
  shell: sudo systemctl enable cups.socket
  tags:
    - base
