- name: Enable multilib 1
  become: true
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"
  tags:
    - base
    - pacman

- name: Enable multilib 2
  become: true
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"
  tags:
    - base
    - pacman

- name: Update Pacman
  become: true
  pacman:
    update_cache: yes
  tags:
    - base
    - pacman
