- name: Install zsh 
  become: true
  pacman:
    name: zsh
  tags:
    - base
    - dotfiles
    - zsh 
- name: Install Oh-My-Zsh
  become: true
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become_user: axelz
  tags:
    - base
    - dotfiles
    - zsh
- name: Change default shell to zsh
  become: true
  shell: "chsh -s $(which zsh) axelz"
  tags:
    - base
    - dotfiles
    - zsh 
- name: Install zsh-syntax-highlighting plugin
  become: true
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  become_user: axelz
  tags:
    - base
    - dotfiles
    - zsh


# - name: Change shell to zsh
#   become: true
#   shell: chsh -s $(which zsh)
#   tags:
#     - base
#     - dotfiles
#     - zsh 
