- name: Install zsh 
  become: true
  pacman:
    name: zsh
  tags:
    - base
    - dotfiles
    - zsh 
- name: Install Oh-My-Zsh
  become: true
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become_user: axelz
  tags:
    - base
    - dotfiles
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - base
    - dotfiles
    - zsh 
